
version: '3'

services:
  db:
    image: 'mysql/mysql-server:5.7'
    ports:
           - "3306:3306"
    environment:
           - MYSQL_ROOT_PASSWORD=Welcome123
           - MYSQL_DATABASE=CRUD
           - MYSQL_USER=root
           - MYSQL_PASSWORD=Welcome123
           - MYSQL_ROOT_HOST=%
    volumes:
           - ./my-datavolume:/var/lib/mysql
    healthcheck:
           test: ["CMD","mysqladmin","ping","-h","localhost"]
           timeout: 20s
           retries: 10
    restart: always
  backendserver:
    build: ./crud-backend/
    ports:
           - "8081"
    links:
           - "db"
    depends_on:
           - "db"
    restart: always
  frontend:
    build: ./CRUD/
    links:
           - "backendserver"
    depends_on:
           - "backendserver"
    ports:
           - "80:80"    