version: '3'

services:
  db:
    image: "mariadb:10.5.8"
    restart: always
    ports:
           - 3306:3306
    environment:
           - MYSQL_ROOT_PASSWORD=toor
  backendserver:
    build: ./Backend/
    restart: always
    ports:
           - "8081:8081"
    depends_on:
           - db
  frontend:
    build: ./FrontEnd/Gestion-Teletrabajo-Frontend/
    links:
           - "backendserver"
    depends_on:
           - "backendserver"
    ports:
           - "80:80" 